#!/bin/bash
echo "🔍 YouClaw Network Diagnostic"
echo "----------------------------"
echo "Internal IP: \$(hostname -I)"
echo "Public IPv4: \$(curl -s -4 ifconfig.me)"
echo "Listening on: \$(ss -tuln | grep :8080)"
echo ""
echo "Try these URLs in your browser:"
echo "1. http://localhost:8080 (If on the same machine)"
echo "2. http://\$(ip route get 1.1.1.1 | awk '{print \$7}'):8080 (If on the same WiFi)"
echo "3. http://\$(curl -s -4 ifconfig.me):8080 (If accessing from outside)"
echo ""
echo "If none work, try opening the port (requires password):"
echo "sudo ufw allow 8080/tcp"
